### GENERAL SETTINGS ###

# Site settings
title: VIANA, C.D.
description: "Personal site and blog of Camila Duelis Viana."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "http://cdviana.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: "https://www.linkedin.com/in/camila-viana-2b63a238"
  - title: facebook
    url: "https://www.facebook.com/camiladviana"
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Av. Professor Luciano Gualberto, 1289, Cidade Universitária
    - 05508-010 - São Paulo – SP – Brasil
    -
    - LatLong -23.558799,-46.735672
    - 23°33’31.68”S, 46°44’8.42”W
    - UTM 23K 322847 E / 7393546 N23890, New York,
email: camila.viana@usp.com
tel: +55 11 3091 2627


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Prof. Carlos Henrique Grohmann
    position: PhD Advisor
    text: He advised me during scientific internship (2009) and undergrad (2012). Head of SPAMLab.
    img: guano1.jpg
    social:
      - title: envelope #use for email address
        url: mailto:guano@usp.br
      - title: page
        url: https://carlosgrohmann.com/

# Clients information. Shown on Home and About pages.
clients:
  - name: SPAMLab
    img: spamlogo.png
#  - name: Code is Poetry
#    img: client02.png
#  - name: Vimeo
#    img: client03.png
#  - name: VimeoPro
#    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "I’m a PhD student at the Institute of Geosciences of the University of São Paulo, Brazil.
My research interests include Photogrammetry, UAVs, LiDAR, Remote Sensing, Free Software (FOSS), DEMs, GIS, Structural Geology, Rock Mechanics and Rock Engineering."

# Testimonial content. Shown on Home and About page.
#testimonial:
#    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
#    author: Marcel Newman
#    position: WEB DESIGNER - BLACKTIE.CO
