### GENERAL SETTINGS ###

# Site settings
title: VIANA, C.D.
description: "Personal site and blog of Camila Duelis Viana."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "http://cdviana.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#2C3531" #"#F70031"
  primary_rgb: "44,53,49" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#116466" #"#33004D"
  link: "#428bca"
  link_hover: "#FFCB9A"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin,twitter, instagram, tumblr etc). Shown in footer.
social:
  - title: linkedin
    url: "https://www.linkedin.com/in/camila-duelis-viana"
  - title: facebook
    url: "https://www.facebook.com/camiladviana"
  - title: orcid
    url: "https://orcid.org/0000-0001-7093-0244"


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Rua do Lago, 562, Cidade Universitária
    - 05508-080 - São Paulo – SP – Brazil
    - 23°33’42.48”S, 46°43’39.87”W

email: camila.viana@usp.br
tel: +55 11 3091 4242


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Prof. Carlos H. Grohmann
    position: Associate Professor - IEE-USP
    text: Head of [SPAMLab](https://spamlab.github.io/). We work together on research related to drones, GIS and digital models. Was my undergrad and PhD supervisor.
    img: guano1.jpg
    social:
#      - title: envelope #use for email address
#        url: mailto:guano@usp.br
      - title: url
        url: https://carlosgrohmann.com/

  - name: Prof. Ginaldo A. C. Campanha
    position: Senior Professor - IGc-USP
    text: We work together on research related to structural geology. Was my MSc supervisor.
    img: Ginaldo-Campanha.jpg
    social:
#      - title: envelope #use for email address
#        url: mailto:guano@usp.br
      - title: url
        url: http://lattes.cnpq.br/2971347311613974

  - name: Prof. Caroline M. Gevaert
    position: Assistant Professor - UT-ITC
    text: We work together on using drone imagery and AI in Brazilian slums.
    img: https://1348661504.rsc.cdn77.org/.uc/fe3d56e1c0101cf71020016616d031ecbe0cc212f968700/fpe-20210908-040.jpg
    social:
#      - title: envelope #use for email address
#        url: mailto:guano@usp.br
      - title: url
        url: https://people.utwente.nl/c.m.gevaert

# Clients information. Shown on Home and About pages.
clients:
  - name: Instituto de Geociências - USP
    img: igclogo.png
  - name: SPAMLab
    img: spamlogo.png



# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "I'm an Assistant Professor for Data Science and Artificial Intelligence in Geoscience at the Institute of Geosciences of the University of São Paulo, Brazil."

# Testimonial content. Shown on Home and About page.
#testimonial:
#    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
#    author: Marcel Newman
#    position: WEB DESIGNER - BLACKTIE.CO
