### GENERAL SETTINGS ###

# Site settings
title: VIANA, C.D.
description: "Personal site and blog of Camila Duelis Viana."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "http://cdviana.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#2C3531" #"#F70031"
  primary_rgb: "44,53,49" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#116466" #"#33004D"
  link: "#428bca"
  link_hover: "#FFCB9A"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin,twitter, instagram, tumblr etc). Shown in footer.
social:
  - title: linkedin
    url: "https://www.linkedin.com/in/camila-duelis-viana"
  - title: facebook
    url: "https://www.facebook.com/camiladviana"


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Rua do Lago, 562, Cidade Universitária
    - 05508-080 - São Paulo – SP – Brazil
    - 23°33’42.48”S, 46°43’39.87”W

email: camila.viana@usp.com
tel: +55 11 3091 4242


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Prof. Carlos Henrique Grohmann
    position: Associate Professor - IEE-USP
    text: Head of [SPAMLab](https://spamlab.github.io/). We work together on research related to drones, GIS and digital models. Was my undergrad and PhD supervisor.
    img: guano1.jpg
    social:
      - title: envelope #use for email address
        url: mailto:guano@usp.br
      - title: url
        url: https://carlosgrohmann.com/

  - name: Prof. Ginaldo A. C. Campanha
    position: Associate Professor - IGc-USP
    text: We work together on research related to structural geology. Was my MSc supervisor.
    img: Ginaldo-Campanha.jpg
    social:
      - title: envelope #use for email address
        url: mailto:guano@usp.br
      - title: url
        url: https://carlosgrohmann.com/

# Clients information. Shown on Home and About pages.
clients:
  - name: Instituto de Geociências - USP
    img: igclogo.png
  - name: SPAMLab
    img: spamlogo.png



# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "I’m a PhD student at the Institute of Geosciences of the University of São Paulo, Brazil.
My research interests include Photogrammetry, UAVs, LiDAR, Remote Sensing, Free Software (FOSS), DEMs, GIS, Structural Geology, Rock Mechanics and Rock Engineering."

# Testimonial content. Shown on Home and About page.
#testimonial:
#    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
#    author: Marcel Newman
#    position: WEB DESIGNER - BLACKTIE.CO
